name: Homie
options:
  bundleIdPrefix: com.homie
  deploymentTarget:
    iOS: "16.0"
    macCatalyst: "13.0"
    macOS: "13.0"
  createIntermediateGroups: true

targets:
  # Mac Catalyst target (current - works on iPad too)
  Homie:
    type: application
    platform: iOS
    supportedDestinations: [iOS, macCatalyst]
    sources:
      - path: Homie
        excludes:
          - "*.entitlements"
          - "macOS/**"
    entitlements:
      path: Homie/Homie.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.homie.app
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_ENTITLEMENTS: Homie/Homie.entitlements
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_STYLE: Automatic
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        TARGETED_DEVICE_FAMILY: "1,2,6"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHomeKitUsageDescription: "Homie needs access to your HomeKit devices to display and control them."
        INFOPLIST_KEY_NSLocalNetworkUsageDescription: "Homie runs a local HTTP server for automation integrations."
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    dependencies:
      - sdk: HomeKit.framework
      - sdk: Network.framework
      - sdk: ServiceManagement.framework

  # Native macOS target (full features - app-aware scenes, menu bar)
  HomieMac:
    type: application
    platform: macOS
    sources:
      - path: Homie
        excludes:
          - "*.entitlements"
      - path: HomieMac
    entitlements:
      path: HomieMac/HomieMac.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.homie.mac
        PRODUCT_NAME: Homie
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_ENTITLEMENTS: HomieMac/HomieMac.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHomeKitUsageDescription: "Homie needs access to your HomeKit devices to display and control them."
        INFOPLIST_KEY_NSLocalNetworkUsageDescription: "Homie runs a local HTTP server for automation integrations."
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
    dependencies:
      - sdk: HomeKit.framework
      - sdk: Network.framework
      - sdk: ServiceManagement.framework
      - sdk: AppKit.framework
